"""UAT test generator.

Generates pytest test files from task context, converting each acceptance
criterion into a test function. Supports four generator categories:
  A) Acceptance tests (from acceptance criteria)
  B) Behavioral tests (from user stories)
  C) Compliance tests (from RFC spec index)
  D) UX compliance tests (from UX design spec index)

Uses programmatic string formatting (no Jinja2 template files).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path  # noqa: TC003 — used at runtime
from typing import TYPE_CHECKING

import structlog

from autopilot.uat.task_context import TaskContext  # noqa: TC001

if TYPE_CHECKING:
    from autopilot.uat.spec_index import SpecIndex

logger = structlog.get_logger(__name__)

# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class GeneratedTestFile:
    """Result of test generation for a single task."""

    file_path: str
    test_count: int
    test_names: list[str] = field(default_factory=list)
    source_code: str = ""


# ---------------------------------------------------------------------------
# Slug helpers
# ---------------------------------------------------------------------------

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slugify(text: str, max_length: int = 60) -> str:
    """Convert text to a valid Python identifier slug."""
    slug = _SLUG_RE.sub("_", text.lower()).strip("_")
    if not slug:
        slug = "criterion"
    return slug[:max_length].rstrip("_")


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

_FILE_HEADER = '''\
"""UAT acceptance tests for task {task_id}: {title}.

Auto-generated by the UAT test generator. Each test corresponds
to an acceptance criterion from the task specification.
"""

from __future__ import annotations

import pytest


'''

_TEST_TEMPLATE = '''\
def test_task_{task_id}_{slug}() -> None:
    """AC: {criterion}"""
    # TODO: implement acceptance test
    # Criterion: {criterion}
    pytest.skip("UAT stub — implement acceptance verification")


'''


class TestGenerator:
    """Generates pytest test files from TaskContext acceptance criteria."""

    def __init__(self, *, max_tests_per_sp: int = 5) -> None:
        self._max_tests_per_sp = max_tests_per_sp

    def generate_acceptance_tests(self, context: TaskContext) -> GeneratedTestFile:
        """Generate a pytest test file from a task's acceptance criteria.

        Each acceptance criterion becomes a ``test_task_{id}_{slug}`` function.
        The total number of generated tests is capped at
        ``max_tests_per_sp * sprint_points``.
        """
        task_id = _sanitize_id(context.task_id)
        criteria = context.acceptance_criteria

        if not criteria:
            logger.warning("no_acceptance_criteria", task_id=context.task_id)

        # Cap test count based on story points
        sp = context.sprint_points
        sp_int = int(sp) if isinstance(sp, int) else 1
        max_tests = self._max_tests_per_sp * max(sp_int, 1)
        criteria = criteria[:max_tests]

        # Build source code
        header = _FILE_HEADER.format(task_id=context.task_id, title=context.title)
        body_parts: list[str] = []
        test_names: list[str] = []
        seen_slugs: set[str] = set()

        for criterion in criteria:
            slug = _unique_slug(_slugify(criterion), seen_slugs)

            name = f"test_task_{task_id}_{slug}"
            test_names.append(name)
            body_parts.append(
                _TEST_TEMPLATE.format(
                    task_id=task_id,
                    slug=slug,
                    criterion=_escape_docstring(criterion),
                )
            )

        source_code = header + "".join(body_parts)
        file_path = f"tests/uat/test_task_{task_id}_uat.py"

        return GeneratedTestFile(
            file_path=file_path,
            test_count=len(test_names),
            test_names=test_names,
            source_code=source_code,
        )

    def write_test_file(self, generated: GeneratedTestFile, project_dir: Path) -> Path:
        """Write the generated test file to disk."""
        out = project_dir / generated.file_path
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(generated.source_code, encoding="utf-8")
        logger.info(
            "test_file_written",
            path=str(out),
            test_count=generated.test_count,
        )
        return out


# ---------------------------------------------------------------------------
# Behavioral test generator (Category B — Task 071)
# ---------------------------------------------------------------------------

_USER_STORY_RE = re.compile(
    r"[Aa]s\s+(?:an?\s+)?(?P<role>.+?),\s+"
    r"I\s+want\s+(?P<action>.+?),\s+"
    r"so\s+that\s+(?P<outcome>.+?)\.?$",
    re.DOTALL,
)

_BEHAVIORAL_HEADER = '''\
"""UAT behavioral tests for task {task_id}: {title}.

Auto-generated from user story. Tests follow Given-When-Then structure.
"""

from __future__ import annotations

import pytest


'''

_BEHAVIORAL_TEMPLATE = '''\
def test_user_story_{task_id}_{slug}() -> None:
    """Behavioral: {description}"""
    # Given: {given}
    # When: {action}
    # Then: {outcome}
    pytest.skip("UAT stub — implement behavioral verification")


'''


def _parse_user_story(story: str) -> dict[str, str]:
    """Parse a user story into role, action, and outcome components."""
    m = _USER_STORY_RE.match(story.strip())
    if m:
        return {
            "role": m.group("role").strip(),
            "action": m.group("action").strip(),
            "outcome": m.group("outcome").strip(),
        }
    return {"role": "user", "action": story.strip(), "outcome": "expected behavior occurs"}


class BehavioralTestGenerator:
    """Generates behavioral tests from user stories (Category B)."""

    def generate_behavioral_tests(self, context: TaskContext) -> GeneratedTestFile:
        """Generate behavioral pytest tests from a task's user story.

        Parses the user story into Given-When-Then structure and generates
        a test function for each testable component.
        """
        task_id = _sanitize_id(context.task_id)
        story = context.user_story
        if not story:
            logger.warning("no_user_story", task_id=context.task_id)
            return GeneratedTestFile(
                file_path=f"tests/uat/test_task_{task_id}_behavioral.py",
                test_count=0,
                source_code="",
            )

        parts = _parse_user_story(story)
        header = _BEHAVIORAL_HEADER.format(task_id=context.task_id, title=context.title)

        test_names: list[str] = []
        body_parts: list[str] = []

        # Generate main user story test
        action_slug = _slugify(parts["action"])
        name = f"test_user_story_{task_id}_{action_slug}"
        test_names.append(name)
        body_parts.append(
            _BEHAVIORAL_TEMPLATE.format(
                task_id=task_id,
                slug=action_slug,
                description=_escape_docstring(story),
                given=_escape_docstring(f"user is a {parts['role']}"),
                action=_escape_docstring(parts["action"]),
                outcome=_escape_docstring(parts["outcome"]),
            )
        )

        # Generate additional tests from acceptance criteria with behavioral keywords
        seen_slugs = {action_slug}
        behavioral_keywords = {"workflow", "flow", "process", "step", "when", "then"}
        for criterion in context.acceptance_criteria:
            lower = criterion.lower()
            if any(kw in lower for kw in behavioral_keywords):
                slug = _unique_slug(_slugify(criterion), seen_slugs)

                name = f"test_user_story_{task_id}_{slug}"
                test_names.append(name)
                body_parts.append(
                    _BEHAVIORAL_TEMPLATE.format(
                        task_id=task_id,
                        slug=slug,
                        description=_escape_docstring(criterion),
                        given=_escape_docstring(f"user is a {parts['role']}"),
                        action=_escape_docstring(criterion),
                        outcome=_escape_docstring(parts["outcome"]),
                    )
                )

        source_code = header + "".join(body_parts)
        file_path = f"tests/uat/test_task_{task_id}_behavioral.py"

        return GeneratedTestFile(
            file_path=file_path,
            test_count=len(test_names),
            test_names=test_names,
            source_code=source_code,
        )


# ---------------------------------------------------------------------------
# Compliance test generator (Category C — Task 072)
# ---------------------------------------------------------------------------

_COMPLIANCE_HEADER = '''\
"""UAT compliance tests for task {task_id}: {title}.

Auto-generated from RFC specification index. Tests verify implementation
against technical specification requirements.
"""

from __future__ import annotations

import pytest


'''

_COMPLIANCE_TEMPLATE = '''\
def test_rfc_{name_slug}() -> None:
    """Compliance: {spec_id} — {requirement}"""
    # Spec: {spec_id} ({section})
    # Requirement: {requirement}
    pytest.skip("UAT stub — implement compliance verification")


'''


class ComplianceTestGenerator:
    """Generates specification compliance tests (Category C)."""

    def generate_compliance_tests(
        self, context: TaskContext, spec_index: SpecIndex
    ) -> GeneratedTestFile:
        """Generate compliance tests from a spec index.

        For each spec entry relevant to the task, generates a test verifying
        the implementation meets the specification requirement.
        """
        task_id = _sanitize_id(context.task_id)
        header = _COMPLIANCE_HEADER.format(task_id=context.task_id, title=context.title)

        test_names: list[str] = []
        body_parts: list[str] = []
        seen_slugs: set[str] = set()

        for entry in spec_index.entries:
            section_slug = _slugify(entry.section, max_length=30)
            req_slug = _slugify(entry.requirement_text, max_length=30)

            combined = _unique_slug(f"{section_slug}_{req_slug}", seen_slugs)

            name = f"test_rfc_{combined}"
            test_names.append(name)
            body_parts.append(
                _COMPLIANCE_TEMPLATE.format(
                    name_slug=combined,
                    spec_id=_escape_docstring(entry.spec_id),
                    section=_escape_docstring(entry.section),
                    requirement=_escape_docstring(entry.requirement_text[:200]),
                )
            )

        source_code = header + "".join(body_parts) if body_parts else ""
        file_path = f"tests/uat/test_task_{task_id}_compliance.py"

        return GeneratedTestFile(
            file_path=file_path,
            test_count=len(test_names),
            test_names=test_names,
            source_code=source_code,
        )


# ---------------------------------------------------------------------------
# UX compliance test generator (Category D — Task 073)
# ---------------------------------------------------------------------------

_UX_HEADER = '''\
"""UAT UX compliance tests for task {task_id}: {title}.

Auto-generated from UX design specification index. Tests verify CLI output,
REPL behavior, and terminal dimensions against UX design spec.
"""

from __future__ import annotations

import pytest


'''

_UX_TEMPLATE = '''\
def test_ux_{name_slug}() -> None:
    """UX Compliance: {spec_id} — {requirement}"""
    # Spec: {spec_id} ({section})
    # Requirement: {requirement}
    pytest.skip("UAT stub — implement UX compliance verification")


'''


class UXTestGenerator:
    """Generates UX compliance tests (Category D)."""

    def generate_ux_tests(self, context: TaskContext, ux_index: SpecIndex) -> GeneratedTestFile:
        """Generate UX compliance tests from a UX design spec index.

        Generates tests for dashboard constraints, prompt format,
        output patterns, and notification tiers.
        """
        task_id = _sanitize_id(context.task_id)
        header = _UX_HEADER.format(task_id=context.task_id, title=context.title)

        test_names: list[str] = []
        body_parts: list[str] = []
        seen_slugs: set[str] = set()

        for entry in ux_index.entries:
            section_slug = _slugify(entry.section, max_length=30)
            req_slug = _slugify(entry.requirement_text, max_length=30)

            combined = _unique_slug(f"{section_slug}_{req_slug}", seen_slugs)

            name = f"test_ux_{combined}"
            test_names.append(name)
            body_parts.append(
                _UX_TEMPLATE.format(
                    name_slug=combined,
                    spec_id=_escape_docstring(entry.spec_id),
                    section=_escape_docstring(entry.section),
                    requirement=_escape_docstring(entry.requirement_text[:200]),
                )
            )

        source_code = header + "".join(body_parts) if body_parts else ""
        file_path = f"tests/uat/test_task_{task_id}_ux.py"

        return GeneratedTestFile(
            file_path=file_path,
            test_count=len(test_names),
            test_names=test_names,
            source_code=source_code,
        )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _sanitize_id(task_id: str) -> str:
    """Make a task ID safe for use in Python identifiers."""
    return re.sub(r"[^a-zA-Z0-9]", "_", task_id).strip("_")


def _escape_docstring(text: str) -> str:
    """Escape text for safe inclusion in a docstring."""
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _unique_slug(base: str, seen: set[str]) -> str:
    """Return a unique slug by appending a counter suffix if needed."""
    slug = base
    counter = 2
    while slug in seen:
        slug = f"{base}_{counter}"
        counter += 1
    seen.add(slug)
    return slug
