"""UAT test generator.

Generates pytest test files from task context, converting each acceptance
criterion into a test function. Uses programmatic string formatting
(no Jinja2 template files).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path  # noqa: TC003 — used at runtime

import structlog

from autopilot.uat.task_context import TaskContext  # noqa: TC001

logger = structlog.get_logger(__name__)

# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class GeneratedTestFile:
    """Result of test generation for a single task."""

    file_path: str
    test_count: int
    test_names: list[str] = field(default_factory=list)
    source_code: str = ""


# ---------------------------------------------------------------------------
# Slug helpers
# ---------------------------------------------------------------------------

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slugify(text: str, max_length: int = 60) -> str:
    """Convert text to a valid Python identifier slug."""
    slug = _SLUG_RE.sub("_", text.lower()).strip("_")
    if not slug:
        slug = "criterion"
    return slug[:max_length].rstrip("_")


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

_FILE_HEADER = '''\
"""UAT acceptance tests for task {task_id}: {title}.

Auto-generated by the UAT test generator. Each test corresponds
to an acceptance criterion from the task specification.
"""

from __future__ import annotations

import pytest


'''

_TEST_TEMPLATE = '''\
def test_task_{task_id}_{slug}() -> None:
    """AC: {criterion}"""
    # TODO: implement acceptance test
    # Criterion: {criterion}
    pytest.skip("UAT stub — implement acceptance verification")


'''


class TestGenerator:
    """Generates pytest test files from TaskContext acceptance criteria."""

    def __init__(self, *, max_tests_per_sp: int = 5) -> None:
        self._max_tests_per_sp = max_tests_per_sp

    def generate_acceptance_tests(self, context: TaskContext) -> GeneratedTestFile:
        """Generate a pytest test file from a task's acceptance criteria.

        Each acceptance criterion becomes a ``test_task_{id}_{slug}`` function.
        The total number of generated tests is capped at
        ``max_tests_per_sp * sprint_points``.
        """
        task_id = _sanitize_id(context.task_id)
        criteria = context.acceptance_criteria

        if not criteria:
            logger.warning("no_acceptance_criteria", task_id=context.task_id)

        # Cap test count based on story points
        sp = context.sprint_points
        sp_int = int(sp) if isinstance(sp, int) else 1
        max_tests = self._max_tests_per_sp * max(sp_int, 1)
        criteria = criteria[:max_tests]

        # Build source code
        header = _FILE_HEADER.format(task_id=context.task_id, title=context.title)
        body_parts: list[str] = []
        test_names: list[str] = []
        seen_slugs: set[str] = set()

        for criterion in criteria:
            slug = _slugify(criterion)

            # Ensure unique slug
            base_slug = slug
            counter = 2
            while slug in seen_slugs:
                slug = f"{base_slug}_{counter}"
                counter += 1
            seen_slugs.add(slug)

            name = f"test_task_{task_id}_{slug}"
            test_names.append(name)
            body_parts.append(
                _TEST_TEMPLATE.format(
                    task_id=task_id,
                    slug=slug,
                    criterion=_escape_docstring(criterion),
                )
            )

        source_code = header + "".join(body_parts)
        file_path = f"tests/uat/test_task_{task_id}_uat.py"

        return GeneratedTestFile(
            file_path=file_path,
            test_count=len(test_names),
            test_names=test_names,
            source_code=source_code,
        )

    def write_test_file(self, generated: GeneratedTestFile, project_dir: Path) -> Path:
        """Write the generated test file to disk."""
        out = project_dir / generated.file_path
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(generated.source_code, encoding="utf-8")
        logger.info(
            "test_file_written",
            path=str(out),
            test_count=generated.test_count,
        )
        return out


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _sanitize_id(task_id: str) -> str:
    """Make a task ID safe for use in Python identifiers."""
    return re.sub(r"[^a-zA-Z0-9]", "_", task_id).strip("_")


def _escape_docstring(text: str) -> str:
    """Escape text for safe inclusion in a docstring."""
    return text.replace("\\", "\\\\").replace('"', '\\"')
